"""empty message

Revision ID: 09875a3c6af3
Revises: 200181a5fcda
Create Date: 2024-12-15 14:03:05.237615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09875a3c6af3'
down_revision = '200181a5fcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
