"""empty message

Revision ID: 761590bdfcbf
Revises: 09875a3c6af3
Create Date: 2024-12-15 14:49:24.872928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761590bdfcbf'
down_revision = '09875a3c6af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
